// Versioned simulation knobs. Saves record the version so future migrations can
// explain balance changes without scattering magic numbers through the engine.
window.GAME_BALANCE = Object.freeze({
  version: 3,
  compositeWeights: Object.freeze({
    scoring: 0.19,
    shooting: 0.14,
    playmaking: 0.14,
    defense: 0.18,
    rebounding: 0.12,
    athleticism: 0.09,
    iq: 0.09,
    potential: 0.05,
  }),
  teamOverallWeights: Object.freeze({ offense: 0.45, defense: 0.4, rebounding: 0.15 }),
  rotationWeights: Object.freeze([2, 1.5, 1.2, 1, 0.8, 0.5, 0.4, 0.3]),
  statShareWeights: Object.freeze([1, 0.82, 0.66, 0.5, 0.4, 0.3, 0.22, 0.16]),
  homeAdvantage: 2.2,
  injuryRate: 0.022,
  moodScoreScale: 0.04,
  lockerRoom: Object.freeze({
    chemistryScale: 0.0012,
    disciplinarianFactor: 0.4,
    freezeTension: 40,
    freezeFactor: 0.62,
    revealBase: 0.07,
    blowupTension: 45,
    blowupChance: 0.14,
    influencePerWeek: 1,
    suppressWeeks: 2,
    pairStarts: 6,
    pactStarts: 12,
    sitFile: 3,
    captainWeek: 6,
    captainTensionMax: 40,
    captainApproval: 0.5,
    cultureWeeks: 8,
    campaignBoost: 0.15,
    blessedTradeValue: 160,
    hometownBond: 60,
    spongeBond: 50,
    dramaWalkHeat: 28,
    gritFreezeTension: 55,
    gritBlowupMult: 1.6,
    pairingTension: 5,
    pactTension: 10,
  }),
  tradeDeadlineWeek: 12,
  undoLimit: 5,
  trade: Object.freeze({
    minimumRatio: 0.92,
    goodRatio: 1,
    strongRatio: 1.15,
    protectedRatio: 1.25,
    pickRound1: 420,
    pickRound2: 160,
    pickYearBonus: 20,
  }),
});
